# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
   workflow_dispatch:
    inputs:
      show_message:
        description: "If failed tests log errors"
        required: true
        default: "false"
        type: boolean

jobs:
    build-test-deploy:

        runs-on: ubuntu-latest

        steps:
        # klona repository
        - name: Checkout code
          uses: actions/checkout@v3

        # ställ in python
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        # installera beroenden
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # kör tester och logga eventuella felmeddelanden
        - name: Run tests and log errors
          run: |
            pytest tests/ || echo "Test failed. Check logs for details."
          continue-on-error: false # fortsätter även om testerna misslyckas

        # skicka loggfiler som artefakter (om testerna misslyckas)
        - name: Upload test logs
          if: failure()
          uses: actions/upload-artifact@v3
          with:
            name: test-logs
            path: pytest.log

        # autentisera till Google Cloud
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        # konfigurera Docker för GCR
        - name: Configure Docker for GCR
          run: gcloud auth configure-docker

        # bygg och tagga Docker-image
        - name: Build Docker image with buildx
          run: docker build -t mystreamlitapp .

        # tagga Docker-image
        - name: Tag Docker image
          run: |
            docker tag mystreamlitapp gcr.io/${{ secrets.GCP_PROJECT_ID }}/mystreamlitapp:latest

        # pusha Docker-image till GCR
        - name: Push Docker image
          run: |
            docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mystreamlitapp:latest
